### ISSUE TITLE
Can't find `zgrab2` output file

### ISSUE THREAD

**Issue by alt-glitch** [SpectralOps/netz#1]
Hi,
I'm running the tool locally using docker. I run the tool using the command:
```
docker run -e PORT_TO_SCAN='80' -e SUBNET_TO_SCAN='<Random Range>' -e ZGRAB2_ENDPOINT='/' -e TASK_DEFINITION='docker' -v /tmp/:/opt/out --network=host netz
```
This generates an output file for `masscan` as `/tmp/masscan-docker.out`
However, I can't seem to find any output/result file for `zgrab2`. Am I doing something wrong here or does the tool simply not generate a `zgrab2` output file? 
How can I get the `zgrab2` output file too?

**Comment by cmpxchg16** [comment]
@alt-glitch 
The output of running it on docker is the `masscan ips:` and the `zgrab2 ips:`
So for instance if you will run against one Google server:

`docker run -e PORT_TO_SCAN='80' -e SUBNET_TO_SCAN='142.250.186.78/32' -e ZGRAB2_ENDPOINT='/' -e TASK_DEFINITION='docker' -v /tmp/:/opt/out --network=host -it netz`

You will see the results as one `masscan ips:` and one `zgrab2 ips:`

**Comment by alt-glitch** [comment]
@cmpxchg16: Understood. I have been following the steps which you just told me. But the issue is that I do **not** see the `zgrab2` IPs. 
![image](https://user-images.githubusercontent.com/52913345/116841822-f627b000-abf7-11eb-904d-a2cb9455a572.png)
I believe I should be able to see the output of `zgrab2` in `zgrab2-docker.out` but as you can see it is empty. If I had to guess, it probably has something to do with the `jq` pipe in `discover.sh`

**Comment by cmpxchg16** [comment]
@alt-glitch thanks for the input.
I understood what misleading, the example using port 9200 assuming it's an elasticsearch, so the `jq` query like you mentioned is for that:
`select(.data.http.result.response.body != null) | select(.data.http.result.response.body|test("lucene_version")) | .ip`

But for simple use like checking an HTTP port 80 server or any other port with HTTP, this query of elasticsearch isn't correct, while the correct one is just checking there is an success answer:

`select(.data.http.result.response.body != null) | select(.data.http.status == "success") | .ip`

What I did, is to change the example to a real HTTP server IP that always being open, and I change the query accordingly, so now if you will run like that:

`docker run -e PORT_TO_SCAN='80' -e SUBNET_TO_SCAN='216.239.38.21/32' -e ZGRAB2_ENDPOINT='/' -e TASK_DEFINITION='docker' -v /tmp/:/opt/out --network=host -it netz`

and you will look into the shell && inside the output file: `cat /tmp/zgrab2-docker.out`, you will see the results correctly.

Hope now it's more clarified.

**Comment by alt-glitch** [comment]
@cmpxchg16
Thank you so much for the clarification :)
To reiterate; for checking different ports supported by `zgrab2`, one would have to write different queries.
Does this tool have a Gitter or Slack where I may ask more questions?

Thank you again.

Edit: To be able to use `zgrab` with more modules, one would need to change the `zgrab2.ini` file inside the docker image. To use different modules I had to come up with my own way. Do correct me if I'm wrong!

**Comment by cmpxchg16** [comment]
@alt-glitch glad to hear :)
Exactly, different queries for any kind of analysis, or without query at all -- and export the whole JSON out, then slice-and-dice externally.
Regarding more modules - yes in the `zgrab2.ini`
No Gitter or Slack for now, we will open in the near future, in the meantime feels free to raise here.
